
prov_to_table = {
        "hubei": "湖北",
        "beijing": "北京",
        "guangdong": "广东",
        "hunan": "湖南",
        "sichuan": "四川",
        "jiangxi": "江西",
        "guizhou": "贵州",
        "shanxi": "陕西",
        "shandong": "山东",
        "gansu": "甘肃",
        "anhui": "安徽",
        "heilongjiang": "黑龙江",
        "shanghai": "上海",
        "zhejiang": "浙江",
        "henan": "河南",
        "shanxi2": "山西",
        "neimenggu": "内蒙古",
        "jiangsu": "江苏",
        "hebei": "河北",
        "xinjiang": "新疆",
        "jilin": "吉林",
        "tianjin": "天津",
        "fujian": "福建",
        "qinghai": "青海",
        "liaonin": "辽宁",
        "chongqin": "重庆",
        "default": "默认",
        "guangxi": "广西",
        "xizang": "西藏",
        "yunnan": "云南",
        "hainan": "海南",
        "ningxia": "宁夏",
        "taiwan": "台湾",
        "hongkong": "香港",
        "aomen": "澳门",
}

module.exports = prov_to_table;
